### ISSUE TITLE
core/plugins.py in no_pydle branch throws exception

### ISSUE THREAD

**Issue by k-e-l-p** [FrozenPigs/Taigabot3#5]
I did run this after merging with taiga3, but when running it on taiga3's own repo i get a different exception

`python` version: `3.8.2`

here's a traceback:
```
Traceback (most recent call last):
  File "Taigabot", line 55, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "Taigabot", line 46, in main
    bot = Taigabot(config, server_name, ssl)
  File "/home/nojus/programming/paprika/bot.py", line 66, in __init__
    self.plugin_mtimes, self.plugins = plugins.reload(
  File "/home/nojus/programming/paprika/core/plugins.py", line 93, in reload
    return mtimes, plugins
UnboundLocalError: local variable 'plugins' referenced before assignment
```

**Comment by ineeee** [comment]
this happens when there are no plugins in the `plugins/` folder and `glob('*.py')` doesn't match anything.

taiga comes with "core" plugins, so unless you `rm plugins/*.py` this shouldnt be happening.

the real issue hasn't been fixed, though. the code should probably check for an empty `plugins` before returning, maybe throw an exception with an useful message.
