### ISSUE TITLE
cloning and running the repository on branch 'no_pydle' throws exception

### ISSUE THREAD

**Issue by k-e-l-p** [FrozenPigs/Taigabot3#6]
python version: `3.8.2`

```
$ python Taigabot
Traceback (most recent call last):
  File "Taigabot", line 55, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "Taigabot", line 45, in main
    ssl = ssl_context(cert, key)
  File "Taigabot", line 26, in ssl_context
    context.load_cert_chain(cert, keyfile=key)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by ineeee** [comment]
seems like you tried to run the bot with sasl enabled but without any keys.

commit 282fe9d2cb440fbf382a8e04552b23a4f0a833ab is stable if you want to try again.
